// eslint-disable-next-line import/prefer-default-export
export const SWR = {
  ANIMAL: '/api/animal',
  FAZENDAS: '/api/fazenda',
  CULTURAS_FAZENDA: '/api/culture/fazenda',
  CULTURE: 'api/culture',
  CULTURE_TYPE: 'api/culture/types',
  COOPERATIVE: 'api/cooperative',
  ASSOCIATION: 'api/association',
  ALFAIA: 'api/alfaia',
  MEIO_ESTACIONARIO: 'api/meio-estacionario',
  MEIO_ESTACIONARIO_TYPE: 'api/meio-estacionario/types',
  INFRAESTRUTURA: 'api/infrastruture',
  INFRAESTRUTURA_TYPE: 'api/infraestrutura/types',
  MACHINE: 'api/machine',
  MACHINE_TYPE: 'api/machine/types',
  EQUIPAMENTO: 'api/equipamento',
  EQUIPAMENTO_TYPE: 'api/equipamento/types',
  HUMAN_RESOURCE: '/api/human-resource',
  USERS: 'api/users',
  TECHNICIAN: 'api/technician',
  PRODUCER: 'api/producer',
  PARTNER: 'api/partner',
  LOGS: '/api/logs',
  NATIONAL_PRODUCTION: '/api/national-production',
  CONSUMPTION: '/api/consumption',
  MARKET_PRICES: '/api/market-prices',
  PROVINCE: '/api/province',
  COUNTY: '/api/county',
};
