const pallete = {
  // PRIMARY
  PRIMARY: '#F7AF1B',
  PRIMARY_LIGTH: '#AC5E1E',
  PRIMARY_DARK: '#AC5E1E',

  // SECONDARY
  SENCODARY: '#AC5E1E',
  SENCODARY_LIGTH: '',
  SENCODARY_DARK: '',

  // STATUS COLOR
  SUCCESS_DARK: '#32CC5D',
  SUCCESS_MAIN: '#3AE780',
  SUCCESS_LIGHT: '#ECF9F3',
  ERROR_DARK: '#C7372C',
  ERROR_MAIN: '#E24A3B',
  ERROR_LIGHT: '#FBEBEA',
  WARNING_DARK: '#FAAB00',
  WARNING_MAIN: '#FBC800',
  WARNING_LIGHT: '#FFF5E5',
} as const;

export default pallete;
